@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
    Object[] elementData
    size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml

@startuml

struct ASensorManager {

}

struct sensors_vector_t {
    union {
        float v[3];
    }
}
@enduml